#!/bin/bash

# number of threads:
for t in 1 2 4 6 8
do
	NUMT=$t
	# number of subdivisions:
	for s in 1 10 100 1000 10000 100000 500000
	do
		NUMTRIALS=$s
		g++ -DNUMTRIALS=$s -DNUMT=$t Source.cpp helper.cpp -o prog -lm -fopenmp
		./prog
	done
done